### ISSUE TITLE
Rename `serach_*_title` to `search_*_title` in system tests

### ISSUE THREAD

**Issue by lucianghinda** [ShortRuby/rubyandrails.info#106]
In the current testing files, there is a typo for a method present in a couple of test files: 

https://github.com/search?q=repo%3AShortRuby%2Frubyandrails.info+serach_&type=code

Two main objectives:
1. Rename the method
2. Extract the method to a helper in `test/helpers` and re-use that method where needed.

**Comment by sarvaiyanidhi** [comment]
Hi @lucianghinda Can I take up this issue to start with my first contribution in this repository with this small fix?

**Comment by lucianghinda** [comment]
@sarvaiyanidhi yes. Thank you very much for wanting to contribute!

**Comment by lucianghinda** [comment]
This was implemented by @sarvaiyanidhi in https://github.com/ShortRuby/rubyandrails.info/pull/111
