### ISSUE TITLE
Add Avo as Admin to simplify the create/update/delete actions

### ISSUE THREAD

**Issue by lucianghinda** [ShortRuby/rubyandrails.info#16]
Currently, there is a mix of routes that are for visitors and routes/actions that are for admins:

- for example, AuthorsController has two types of actions: one for visitors presenting the information and one for admin. They are very different but share the same page

Thus we need to add Avo as our Admin dashboard.

For this there are a couple of actions to be done:
- [ ] Add Avo
- [ ] Make Avo to be accessible only by authenticated users
- [ ] Configure Avo for Books

**Comment by adrianthedev** [comment]
I picked this up. Pushing an update soon.

**Comment by lucianghinda** [comment]
@adrianthedev this is now live
