### ISSUE TITLE
Implement Promo for FriendlyRB conference

### ISSUE THREAD

**Issue by lucianghinda** [ShortRuby/rubyandrails.info#27]
## Approach

Add the following banner as a link below the main menu with the following attributes:

URL: `https://friendlyrb.com?rel=rubyandrails.info&utm_source=rubyandrails.info`
target: `_blank`
img alt: `Friendly.rb - Your friendly European Ruby Conference.`
caption below: `<strong>Friendly.rb</strong> - Your friendly European Ruby Conference`

![friendlyrb-docs](https://user-images.githubusercontent.com/1334409/226275325-c4f5f222-3e2a-48e1-9e31-f8e63b4e3c17.png)

## Why

[rubyandrails.info](https://rubyandrails.info) is part of [ShortRuby](https://shortruby.com) and we are supporting the organisation of [Friendly.rb](https://friendlyrb.com)

**Comment by adrianthedev** [comment]
I think this is the space to have it for the best exposure.

![](https://cdn.discordapp.com/attachments/1072110200808538152/1087277689804701706/CleanShot_2023-03-20_at_09.32.522x.png)

**Comment by lucianghinda** [comment]
@adrianthedev I agree with the placeholder. 

If possible can you attach here some assets? I know we have some here https://friendlyrb.com/assets but I am thinking that maybe in that sidebar we want a different format of an image?

**Comment by adrianthedev** [comment]
I updated the ticket description so the approach is top-level.

**Comment by lucianghinda** [comment]
I updated the URL to include `utm_source`

**Comment by adrianthedev** [comment]
http://beginnerbounties.com/my/bounties/18

**Comment by pratiktamang** [comment]
I can take this! Seems to be quick change. A link_to helper with image nested underneath. I also set CSS to hide it on smaller window with: "hidden lg:block"

<img width="491" alt="image" src="https://user-images.githubusercontent.com/29284404/226288465-9b5bdd51-bdc5-4c0d-b1d9-4368b2fbf394.png">

**Comment by adrianthedev** [comment]
That looks good! Thanks!

**Comment by pratiktamang** [comment]
Awesome! @adrianthedev PR: https://github.com/ShortRuby/rubyandrails.info/pull/28
