### ISSUE TITLE
Courses cards lack formatting

### ISSUE THREAD

**Issue by divagueame** [ShortRuby/rubyandrails.info#46]
Go to:
https://rubyandrails.info/courses
Scroll down to the bottom.
The last 4 cards lack proper formatting.

![Firefox_Screenshot_2023-03-23T19-12-50 490Z](https://user-images.githubusercontent.com/54085409/227323356-afdd1fb7-a4ff-4cf8-aff5-8b052cc07287.png)

**Comment by lucianghinda** [comment]
@divagueame thank you very much for reporting this. I created a fix at https://github.com/ShortRuby/rubyandrails.info/pull/52

**Comment by divagueame** [comment]
Hi, a similar bug happens on:
https://rubyandrails.info/books?page=3

![image](https://user-images.githubusercontent.com/54085409/227646298-ae06ece1-89be-4cf4-b1d5-34f55bab1894.png)
